_commit: v0.5.5
_src_path: https://github.com/will-rice/papers-template.git
project_name: Voice Design Papers
project_slug: voice-design-papers
template_version: 0.4.9
topic_description: Voice design research papers
